---

variables:
  ANSIBLE_FORCE_COLOR: "true"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - test

before_script:
  - pip install --upgrade pip
  - pip install ansible-core ansible-lint

test:
  image: docker.io/library/python:3.11
  stage: test
  script:
    - ansible-lint .
