---

- name: Debug certificate files location.
  ansible.builtin.debug:
    msg:
      - "Private key file: {{ _acme_cf_files_dir }}/{{ domain }}.private.key"
      - "CSR file: {{ _acme_cf_files_dir }}/{{ domain }}.csr."
      - "Cert file (.crt): {{ _acme_cf_files_dir }}/{{ domain }}.crt."
      - "Cert file (.p12): {{ _acme_cf_files_dir }}/{{ domain }}.p12."
      - "Intermediate file: {{ _acme_cf_files_dir }}/{{ domain }}.intermediate.crt."
      - "Fullchain cert file: {{ _acme_cf_files_dir }}/{{ domain }}.fullchain.crt."
  tags: [debug]
